# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('P1', '0002_auto_20170719_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
    ]
