# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P1', '0004_auto_20170719_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
